// =============================================================================
// REGIONS — the active-data layer (v12).
// =============================================================================
// A "region" is a named set of counties (eBird region codes). The app loads
// only the active region's per-county data files (data/counties/<code>.json),
// so statewide coverage never bloats one download. Switching regions (v14 UI:
// header pills + the county-picker map) just points this module at a different
// county set and re-renders.
//
// This module also owns SPECIES CODE RESOLUTION: species.js is keyed by common
// name and carries no codes, so on boot we load data/taxonomy.json (name→code,
// generated by the pipeline against the live eBird taxonomy) and attach a
// `.code` to each species. Species whose name isn't in the taxonomy yet (e.g. a
// new species before the next pipeline run) simply get no code — their eBird
// link and live badge are hidden, and they won't match county data, but the app
// keeps working. This is what makes wrong hand-typed codes impossible.
//
// County files are keyed by locId and hold: { locId, name, lat, lng, nSpecies,
// freqByMonth: { <code>: [12] }, checklistsByMonth: [12] }. Where a hotspot's
// locId matches one of the hand-curated hotspots in data/hotspots.js, we overlay
// its friendly id, habitats and access notes.
// =============================================================================

import { SPECIES } from '../data/species.js';
import { HOTSPOTS as CURATED } from '../data/hotspots.js';
import { REGIONS, COUNTIES } from '../data/counties.js';

// Region definitions live in data/counties.js (shared with the build pipeline):
// REGIONS is the built-in seed set (Home + Humboldt), always present and not
// editable. On top of that the user can save up to MAX_SAVED regions ON-DEVICE
// (localStorage) via the county-picker map (v14). `regions()` returns the seed
// regions followed by the saved ones. Home is active by default.
export { REGIONS };

const SAVED_KEY = 'frame.regions';
export const MAX_SAVED = 3;

function loadSaved() {
  try {
    const a = JSON.parse(localStorage.getItem(SAVED_KEY) || '[]');
    return Array.isArray(a) ? a.filter((r) => r && r.id && Array.isArray(r.counties)) : [];
  } catch { return []; }
}
function persistSaved(list) {
  try { localStorage.setItem(SAVED_KEY, JSON.stringify(list)); } catch {}
}

/** All regions the switcher shows: built-in seeds first, then saved regions. */
export function regions() { return [...REGIONS, ...loadSaved()]; }
export function savedRegions() { return loadSaved(); }
export function isDefaultRegion(id) { return REGIONS.some((r) => r.id === id); }
export function canAddRegion() { return loadSaved().length < MAX_SAVED; }

function uniqueId(name, saved) {
  const base = 'r-' + (name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'region');
  const taken = new Set([...REGIONS.map((r) => r.id), ...saved.map((r) => r.id)]);
  if (!taken.has(base)) return base;
  let i = 2; while (taken.has(`${base}-${i}`)) i++;
  return `${base}-${i}`;
}

/**
 * Create or update a saved region. Pass an existing saved `id` to update it;
 * omit it (or pass a built-in id) to mint a new one. County codes are validated
 * against the vocabulary and de-duplicated. Returns the region id, or null when
 * a brand-new region would exceed MAX_SAVED (the caller reports it honestly).
 */
export function saveRegion({ id, name, counties }) {
  const saved = loadSaved();
  name = (name || '').trim() || 'My region';
  counties = [...new Set(counties)].filter((c) => COUNTIES[c]);
  if (id && !isDefaultRegion(id)) {
    const i = saved.findIndex((r) => r.id === id);
    if (i >= 0) saved[i] = { id, name, counties };
    else saved.push({ id, name, counties }); // restoring a deleted region by id
  } else {
    // Minting a brand-new region: enforce the cap the UI advertises. Without
    // this, the #/import share-link flow could create a 4th saved region.
    if (saved.length >= MAX_SAVED) return null;
    id = uniqueId(name, saved);
    saved.push({ id, name, counties });
  }
  persistSaved(saved);
  return id;
}

/**
 * Delete a saved region. If it was active, fall back to Home. Returns the
 * removed region plus whether it had been active, so the caller can offer a
 * full undo (re-save it and restore the active selection).
 */
export function deleteRegion(id) {
  const removed = loadSaved().find((r) => r.id === id) || null;
  const wasActive = _activeId === id;
  persistSaved(loadSaved().filter((r) => r.id !== id));
  if (wasActive) setActiveRegion('home');
  return { removed, wasActive };
}

const CURATED_BY_LOCID = Object.fromEntries(CURATED.filter((h) => h.locId).map((h) => [h.locId, h]));

let _activeId = loadSavedActiveId();
let _hotspots = [];
let _meta = { loaded: false, region: null, builtAt: null, counties: 0, hotspots: 0, taxonomy: 0 };
let _codeIndex = {}; // code → species (built after taxonomy attaches)

function loadSavedActiveId() {
  try { return localStorage.getItem('frame.region') || 'home'; } catch { return 'home'; }
}

export function regionMeta() { return _meta; }
export function getHotspots() { return _hotspots; }
export function speciesByCode(code) { return _codeIndex[code]; }

/**
 * Geographic center of the active region (average of its loaded hotspots), or
 * null before data loads. Used to aim the live eBird overlay — both the
 * "seen recently" badges and the species pages' nearest-sighting line — at
 * wherever the planner currently is, instead of a fixed home point.
 */
export function regionCenter() {
  if (!_hotspots.length) return null;
  return {
    lat: _hotspots.reduce((a, h) => a + h.lat, 0) / _hotspots.length,
    lng: _hotspots.reduce((a, h) => a + h.lng, 0) / _hotspots.length,
  };
}

/**
 * Live-overlay search radius (km) sized to the active region: half the
 * hotspot bounding-box diagonal plus a 10 km cushion, clamped to 25–50 km
 * (50 is the eBird API's maximum). A compact region stays tight; a sprawling
 * multi-county region gets as much reach as the API allows.
 */
export function regionOverlayDist() {
  if (_hotspots.length < 2) return 30;
  let minLat = Infinity, maxLat = -Infinity, minLng = Infinity, maxLng = -Infinity;
  for (const h of _hotspots) {
    if (h.lat < minLat) minLat = h.lat; if (h.lat > maxLat) maxLat = h.lat;
    if (h.lng < minLng) minLng = h.lng; if (h.lng > maxLng) maxLng = h.lng;
  }
  const midLat = ((minLat + maxLat) / 2) * Math.PI / 180;
  const dLatKm = (maxLat - minLat) * 111;
  const dLngKm = (maxLng - minLng) * 111 * Math.cos(midLat);
  const diag = Math.hypot(dLatKm, dLngKm);
  return Math.round(Math.min(50, Math.max(25, diag / 2 + 10)));
}

export function activeRegion() { return regions().find((r) => r.id === _activeId) || REGIONS[0]; }

export function setActiveRegion(id) {
  if (!regions().some((r) => r.id === id)) return;
  _activeId = id;
  try { localStorage.setItem('frame.region', id); } catch {}
}

// Attach codes to SPECIES from the generated taxonomy map (once).
let _taxonomyAttached = false;
async function attachCodes() {
  if (_taxonomyAttached) return _meta.taxonomy;
  let map = {};
  try {
    const res = await fetch('./data/taxonomy.json', { cache: 'no-cache' });
    if (res.ok) map = await res.json();
  } catch { /* no taxonomy yet → codes stay undefined, app degrades gracefully */ }
  let n = 0;
  _codeIndex = {};
  for (const s of SPECIES) {
    const code = map[s.name];
    if (code) { s.code = code; _codeIndex[code] = s; n++; }
    else delete s.code;
  }
  _taxonomyAttached = true;
  _meta.taxonomy = n;
  return n;
}

/**
 * Load the active region's county data into the working hotspot list. Safe to
 * call repeatedly (on region switch). Missing county files are skipped, so a
 * region whose data hasn't been built yet just yields fewer hotspots.
 */
export async function loadActiveRegion() {
  await attachCodes();
  const region = activeRegion();
  const hotspots = [];
  let counties = 0;
  let builtAt = null;
  for (const code of region.counties) {
    let data;
    try {
      const res = await fetch(`./data/counties/${code}.json`, { cache: 'no-cache' });
      if (!res.ok) continue;
      data = await res.json();
    } catch { continue; }
    counties++;
    if (data.builtAt && (!builtAt || data.builtAt > builtAt)) builtAt = data.builtAt;
    for (const h of data.hotspots || []) {
      const curated = h.locId ? CURATED_BY_LOCID[h.locId] : null;
      hotspots.push({
        id: curated?.id || h.locId,
        name: curated?.name || h.name,
        locId: h.locId,
        lat: h.lat,
        lng: h.lng,
        county: code,
        habitats: curated?.habitats,          // undefined for uncurated hotspots
        access: curated?.access || null,
        freqByMonth: h.freqByMonth || null,
        checklistsByMonth: h.checklistsByMonth || null,
      });
    }
  }
  _hotspots = hotspots;
  _meta = { loaded: true, region: region.name, builtAt, counties, hotspots: hotspots.length, taxonomy: _meta.taxonomy };
  return _meta;
}
