// =============================================================================
// REGIONS — the active-data layer (v12).
// =============================================================================
// A "region" is a named set of counties (eBird region codes). The app loads
// only the active region's per-county data files (data/counties/<code>.json),
// so statewide coverage never bloats one download. Switching regions (v13 UI)
// just points this module at a different county set and re-renders.
//
// This module also owns SPECIES CODE RESOLUTION: species.js is keyed by common
// name and carries no codes, so on boot we load data/taxonomy.json (name→code,
// generated by the pipeline against the live eBird taxonomy) and attach a
// `.code` to each species. Species whose name isn't in the taxonomy yet (e.g. a
// new species before the next pipeline run) simply get no code — their eBird
// link and live badge are hidden, and they won't match county data, but the app
// keeps working. This is what makes wrong hand-typed codes impossible.
//
// County files are keyed by locId and hold: { locId, name, lat, lng, nSpecies,
// freqByMonth: { <code>: [12] }, checklistsByMonth: [12] }. Where a hotspot's
// locId matches one of the hand-curated hotspots in data/hotspots.js, we overlay
// its friendly id, habitats and access notes.
// =============================================================================

import { SPECIES } from '../data/species.js';
import { HOTSPOTS as CURATED } from '../data/hotspots.js';
import { REGIONS } from '../data/counties.js';

// Region definitions live in data/counties.js (shared with the build pipeline).
// v12 scope: Home + Humboldt. Home is active by default.
export { REGIONS };

const CURATED_BY_LOCID = Object.fromEntries(CURATED.filter((h) => h.locId).map((h) => [h.locId, h]));

let _activeId = loadSavedActiveId();
let _hotspots = [];
let _meta = { loaded: false, region: null, builtAt: null, counties: 0, hotspots: 0, taxonomy: 0 };
let _codeIndex = {}; // code → species (built after taxonomy attaches)

function loadSavedActiveId() {
  try { return localStorage.getItem('frame.region') || 'home'; } catch { return 'home'; }
}

export function regions() { return REGIONS; }
export function activeRegion() { return REGIONS.find((r) => r.id === _activeId) || REGIONS[0]; }
export function regionMeta() { return _meta; }
export function getHotspots() { return _hotspots; }
export function speciesByCode(code) { return _codeIndex[code]; }

export function setActiveRegion(id) {
  if (!REGIONS.some((r) => r.id === id)) return;
  _activeId = id;
  try { localStorage.setItem('frame.region', id); } catch {}
}

// Attach codes to SPECIES from the generated taxonomy map (once).
let _taxonomyAttached = false;
async function attachCodes() {
  if (_taxonomyAttached) return _meta.taxonomy;
  let map = {};
  try {
    const res = await fetch('./data/taxonomy.json', { cache: 'no-cache' });
    if (res.ok) map = await res.json();
  } catch { /* no taxonomy yet → codes stay undefined, app degrades gracefully */ }
  let n = 0;
  _codeIndex = {};
  for (const s of SPECIES) {
    const code = map[s.name];
    if (code) { s.code = code; _codeIndex[code] = s; n++; }
    else delete s.code;
  }
  _taxonomyAttached = true;
  _meta.taxonomy = n;
  return n;
}

/**
 * Load the active region's county data into the working hotspot list. Safe to
 * call repeatedly (on region switch). Missing county files are skipped, so a
 * region whose data hasn't been built yet just yields fewer hotspots.
 */
export async function loadActiveRegion() {
  await attachCodes();
  const region = activeRegion();
  const hotspots = [];
  let counties = 0;
  let builtAt = null;
  for (const code of region.counties) {
    let data;
    try {
      const res = await fetch(`./data/counties/${code}.json`, { cache: 'no-cache' });
      if (!res.ok) continue;
      data = await res.json();
    } catch { continue; }
    counties++;
    if (data.builtAt && (!builtAt || data.builtAt > builtAt)) builtAt = data.builtAt;
    for (const h of data.hotspots || []) {
      const curated = h.locId ? CURATED_BY_LOCID[h.locId] : null;
      hotspots.push({
        id: curated?.id || h.locId,
        name: curated?.name || h.name,
        locId: h.locId,
        lat: h.lat,
        lng: h.lng,
        county: code,
        habitats: curated?.habitats,          // undefined for uncurated hotspots
        access: curated?.access || null,
        outsideBox: curated?.outsideBox || false,
        freqByMonth: h.freqByMonth || null,
        checklistsByMonth: h.checklistsByMonth || null,
      });
    }
  }
  _hotspots = hotspots;
  _meta = { loaded: true, region: region.name, builtAt, counties, hotspots: hotspots.length, taxonomy: _meta.taxonomy };
  return _meta;
}
